### ISSUE TITLE
Policy for Kubernetes manifests with multiple resource definitions of same kind

### ISSUE THREAD

**Issue by amitsaha** [instrumenta/conftest#103]
Hi all, thank you for this tool. Gives me some hope of taming the madness. Consider the following Kubernetes manifest which will create two service accounts:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: x1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: x2
```

I want to write a policy file which will pass only iff both the service accounts are specified with the names `x1` and `x2`.

It's my very early days with rego, and the following policy will *only* work if the names do not match. It will not fail if only one of the service account is defined or both the service accounts have the same name.

```
  empty(value) {
     count(value) == 0
  }

 allow = true  {
   empty(deny)
  }

 deny[msg] {
   input.kind = "ServiceAccount"
   not input.metadata.name == "x1"
   not input.metadata.name == "x2"
   msg = "expected service account not being created"
 } 
 ```
Any suggestions/pointers will be appreciated, thank you.
