### ISSUE TITLE
simple policy does not work

### ISSUE THREAD

**Issue by v-ymarchanka** [instrumenta/conftest#128]
Hey! I have troubles running simple check:
```
# conftest --version
Version: 0.14.0
Commit: 33cb7c6
Date: 2019-10-04T14:31:10Z
```
```
# cat policy/combine.rego 
package example.rules


deny[msg] {
  deployment := "foo"
  service := "bar"

  deployment != service

  msg = sprintf("Expected these values to be the same but received %v for deployment and %v for service", [deployment, service])
}

```
```
# conftest test foo.yaml --trace
Enter data.main.deny = _
| Eval data.main.deny = _
| Fail data.main.deny = _
Enter data.main.deny = _
| Eval data.main.deny = _
| Fail data.main.deny = _

```

if I try the same [here](https://play.openpolicyagent.org/p/2YOLEAngRM) - it works fine
![image](https://user-images.githubusercontent.com/46332393/67409999-67a98b80-f589-11e9-8599-0d8aa42cca00.png)

did I miss configured something? Or bug?

Thanks!

**Comment by jpreese** [comment]
By default, the data is pulled from the `main` package. Looking at your example, you're using `example.rules`.

You'll need to use the `--namespace` flag to pass in `example.rules`

**Comment by v-ymarchanka** [comment]
thanks for answer!

**Comment by jpreese** [comment]
No problem, anytime! Thanks for using conftest 👍

**Comment by v-ymarchanka** [comment]
Sorry for another stupid question but I'm not able to understand why this one is not working(followed by [README.md](https://github.com/instrumenta/conftest#--combine-flag)):
```
# conftest --version                               
Version: 0.14.0
Commit: 33cb7c6
Date: 2019-10-04T14:31:10Z
```
```
# cat policy/combine.rego 
package main


deny[msg] {

  deployment := input["../deployment.yaml"]
  service := "bar"

  deployment != service

  msg = sprintf("Expected these values to be the same but received %v for deployment and %v for service", [deployment, service])
}

```
```
# cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080

```
```
# conftest test *.yaml --trace --combine-config
Enter data.main.deny = _
| Eval data.main.deny = _
| Index data.main.deny = _ matched 0 rules)
| Exit data.main.deny = _
Redo data.main.deny = _
| Redo data.main.deny = _

```
Could you, please, point me to proper section of documentation where I can debug variables easily?
smth like:
```
package main

deployment := input["../deployment.yaml"]
service := "bar"

sprintf("deployment: %v", [deployment])
sprintf("service: %v", [service])
 
```
Thank you!

**Comment by v-ymarchanka** [comment]
I still don't understand how to use it:
```
# cat policy/combine.rego
package main

deployment := input["../deployment.yaml"]
service := "bar"

showvalues[[service, deployment]] {
  sprintf("deployment: %v", [deployment])
  sprintf("service: %v", [service])
}

data.showvalues(service, deployment)

```
```
# cat deployment.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080

```
```
# conftest test deployment.yaml --trace
# echo $?
0
```
I installed conftest using this manual: [link](https://github.com/instrumenta/conftest#installation)
Policies are located in `policy` dir.
Kubernetes yaml manifests are in `.`
Any suggestions?

Thanks

**Comment by jpreese** [comment]
Given your above scenario, you should be able to drop the brackets on `input` 
ex:
`input["../deployment.yaml"]`

Can just be `input`

```
# cat policy/combine.rego
package main

showvalues[[service, deployment]] {
  deployment := input
  service := "bar"
}
```

**Comment by v-ymarchanka** [comment]
nope :(
```
# cat policy/combine.rego              
package main

showvalues[[service, deployment]] {
  deployment := input
  service := "bar"
}

```
```
# conftest test deployment.yaml --trace
# echo $?                              
0
```
No output at all

-------------------------
I was not able to reproduce this example also: [link](https://github.com/instrumenta/conftest#--combine-flag)

conftest expecting `--combine-config` not `--combine` but it does not make any difference:

```
# cat service.yaml 
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: goodbye-kubernetes
```
`deployment.yaml` the same as in example above
```
# conftest test deployment.yaml service.yaml --combine-config --trace
Enter data.main.deny = _
| Eval data.main.deny = _
| Index data.main.deny = _ matched 0 rules)
| Exit data.main.deny = _
Redo data.main.deny = _
| Redo data.main.deny = _

```

**Comment by jpreese** [comment]
Ah, at least when using `conftest`, it looks like the rule has to be `deny` or `warn`, so to get a value out of your deployment manifest:

```
package main

deny[msg] {
  msg = input.kind
}
```

**Comment by v-ymarchanka** [comment]
Looks like a bug with `--combine-config` option:

policy/combine.rego:
```
package main

deny[msg] {

  s := "foo"
  f := "bar"

  s != f

  msg = input.kind
}
```
deployment-and-service.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: goodbye-kubernetes
```
deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
```
service.yaml:
```
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: goodbye-kubernetes
```
# empty output use `--combine-config`:
```
> conftest test deployment.yaml service.yaml --combine-config --debug --trace
Enter data.main.deny = _
| Eval data.main.deny = _
| Index data.main.deny = _ matched 0 rules)
| Exit data.main.deny = _
Redo data.main.deny = _
| Redo data.main.deny = _
```
# output with data:
```
> cat deployment-and-service.yaml | conftest test -                         
FAIL - Deployment
FAIL - Service
```
```
> conftest test service.yaml --trace
Enter data.main.deny = _
| Eval data.main.deny = _
| Index data.main.deny = _ (matched 1 rule)
| Enter data.main.deny
| | Eval __local0__ = "foo"
| | Eval __local1__ = "bar"
| | Eval neq(__local0__, __local1__)
| | Eval msg = input.kind
| | Exit data.main.deny
| Redo data.main.deny
| | Redo msg = input.kind
| | Redo neq(__local0__, __local1__)
| | Redo __local1__ = "bar"
| | Redo __local0__ = "foo"
| Exit data.main.deny = _
Redo data.main.deny = _
| Redo data.main.deny = _
FAIL - service.yaml - Service
```
```
> conftest test service.yaml deployment.yaml --trace 
Enter data.main.deny = _
| Eval data.main.deny = _
| Index data.main.deny = _ (matched 1 rule)
| Enter data.main.deny
| | Eval __local0__ = "foo"
| | Eval __local1__ = "bar"
| | Eval neq(__local0__, __local1__)
| | Eval msg = input.kind
| | Exit data.main.deny
| Redo data.main.deny
| | Redo msg = input.kind
| | Redo neq(__local0__, __local1__)
| | Redo __local1__ = "bar"
| | Redo __local0__ = "foo"
| Exit data.main.deny = _
Redo data.main.deny = _
| Redo data.main.deny = _
FAIL - service.yaml - Service
Enter data.main.deny = _
| Eval data.main.deny = _
| Index data.main.deny = _ (matched 1 rule)
| Enter data.main.deny
| | Eval __local0__ = "foo"
| | Eval __local1__ = "bar"
| | Eval neq(__local0__, __local1__)
| | Eval msg = input.kind
| | Exit data.main.deny
| Redo data.main.deny
| | Redo msg = input.kind
| | Redo neq(__local0__, __local1__)
| | Redo __local1__ = "bar"
| | Redo __local0__ = "foo"
| Exit data.main.deny = _
Redo data.main.deny = _
| Redo data.main.deny = _
FAIL - deployment.yaml - Deployment
```
