### ISSUE TITLE
how to get value from map using `--combine-config`

### ISSUE THREAD

**Issue by v-ymarchanka** [instrumenta/conftest#138]
Hey!
I walked though the issue: [#106](https://github.com/instrumenta/conftest/issues/106) and created simple .yaml manifest:
```
foo: bar
---
bar: foo
---
k: f
```
rego.policy:
```
package main

warn[msg] {
  data = yaml.marshal(input)
  msg = data[_]
}
```
run `conftest test test.yaml --combine-config`. output:
```
FATA[0000] Problem building rego compiler: 1 error occurred: combine.rego:5: rego_type_error: undefined ref: __local0__[_]
        __local0__[_]
        ^^^^^^^^^^
        have: string 

```
or
```
package main

warn[msg] {
  data := yaml.marshal(input)
  msg = data["test.yaml"]
}
```
output:
```
FATA[0000] Problem building rego compiler: 1 error occurred: combine.rego:5: rego_type_error: undefined ref: __local0__["test.yaml"]
        __local0__["test.yaml"]
        ^^^^^^^^^^
        have: string 
```

it works fine if policy is:
```
package main

warn[msg] {
  data := yaml.marshal(input)
  msg = data
}
```

This issue might look stupid, but I don't understand why this is not working.
Need help :pray: 

Thanks!

**Comment by v-ymarchanka** [comment]
We have repository with multi level structure that updates frequently.
Combine all configs in one big manifest is really useful and, I guess, only the one way acceptable for us(we don't want to update policies or shell script after new manifests added).

Ideas:
1. To be able to identify duplicates before they will be sent to Kubertenes for deploy.
I'm trying to make process less time consuming and reject duplicate entries on `check config` stage.
example from [OPA](https://www.openpolicyagent.org/docs/latest/policy-language/#comprehensions) docs:
```
no_bitcoin_miners_using_comprehension {
    bitcoin_miners := {app | app := apps[_]; app.name == "bitcoin-miner"}
    count(bitcoin_miners) == 0
}
```

2. As long as #1 will be achieved, it will give me opportunity to compare different labels from different kinds like mentioned in this [example](https://github.com/instrumenta/conftest#--combine-flag) without specifying file names in policy.

3. It would be great to have functionality described above in rego policies instead of writing separate script.

4. Getting through this will give me better view and understanding how Rego works. Maybe entire design is not applicable and has to be re-implemented.

And anyhow: as long as all input assigned to single variable `data := yaml.marshal(input)` I would like to know what am I doing wrong unable to reference this data in the code.

Does it make sense?

Thanks for answer!

**Comment by jpreese** [comment]
> And anyhow: as long as all input assigned to single variable `data := yaml.marshal(input)` I would like to know what am I doing wrong unable to reference this data in the code.

`yaml.marshal` is going to return a `string`, not an array you'd be able to index. In this case, you're trying to use a `string` in a way its not intended. So you can assign/return/print it just fine.

**Comment by v-ymarchanka** [comment]
got it!
Is here any way to create structured data from input so I can iterate over it then?

Thanks!

**Comment by jpreese** [comment]
I'm quite sure I follow, generally the input to conftest is already structured. 

Are you looking for something like `conftest parse test.yaml | conftest test -` . ?

**Comment by v-ymarchanka** [comment]
sorry for being specific not enough.
lets say I have multi doc yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.5
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: goodbye-kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: goodbye-kubernetes
```

And lets say I want to be sure that `there is only one Service with name hello-kubernetes` in this file
Is that possible to create single variable with list to iterate over it and find duplicates?

Thanks!
