### ISSUE TITLE
Extend conftest using preprocessor plugins

### ISSUE THREAD

**Issue by Blokje5** [instrumenta/conftest#226]
In #221 there was a discussion on adding a mechanism to extend conftest using plugins. This issue can be used to discuss the proposal.

Currently the intention is to use plugins as preprocessors, i.e. commands that run at a certain point in the testing cycle. For example, a command could run pre-parsing to parse an unknown input for conftest into something it could process. Or it could expand on the input (e.g. render a helm template).

Plugins will be described using a plugin.yaml, which contains relevant metadata, such as a name, version and a description along with a command that should be run at a certain point in the process:

```yaml
name: "test"
version: "0.1.0"
description: |-
  long description
processor: 
  pre-parse: $PLUGIN_DIR/my-command.sh
```

A flag will be added to conftest to specify which plugin to run, e.g. `--plugin <remote-plugin-location>` or `--plugin <local-on-disk-plugin`. Most likely the go-getter library will be reused for fetching plugins from git, http, etc.. For the moment I think we will only allow one plugin to run at a time.

To prevent plugins from being fetched from a remote location on every run, I think a caching directory would be a great idea. `~/.conftest` could be used to store both the plugins along with a file containing the following:

```yaml
plugin:
  name: ...
  version: ...
  directory: ...
  remote-location: ...
```

The plugins themselves can be written in any language and are expected to read input from stdin. This could for example be a list of helm charts to render. The plugins are then expected to return the output to stdout in a format parseable by conftest (preferably json). Multiple outputs could be delimited by a newline.
