### ISSUE TITLE
Repository names including `port` gets treated to contain tags

### ISSUE THREAD

**Issue by kenfdev** [instrumenta/conftest#24]
Hi, thanks for this awesome project :) I've been trying to use an OCI registry to push and pull the policies and hit a problem.

I have a `conftest.toml` as follows:

```toml
policy = "policy"

[[policies]]
repository = "localhost:5000/conftest-circleci"
tag = "latest"
```

It's pointing to my local docker registry but fails to pull it on `conftest update`.

```bash
$ conftest --debug update
INFO[0000] Downloading: localhost:5000/conftest-circleci
FATA[0000] Downloading policy failed: object required
```

It looks like it's missing the `tag` because the `localhost:5000` is containing a `:` and conftest thinks the string already contains a tag.

https://github.com/instrumenta/conftest/blob/master/conftest.go#L323
