### ISSUE TITLE
Error on Kubernetes recommended labels

### ISSUE THREAD

**Issue by nlamirault** [instrumenta/conftest#304]
I've got an error on labels : 

```rego

recommended_labels {
  input.metadata.labels["app.kubernetes.io/name"]
  input.metadata.labels["app.kubernetes.io/instance"]
  input.metadata.labels["app.kubernetes.io/version"]
  input.metadata.labels["app.kubernetes.io/component"]
  input.metadata.labels["app.kubernetes.io/part-of"]
  input.metadata.labels["app.kubernetes.io/managed-by"]
}


warn[msg] {
  kubernetes.is_deployment
  not recommended_labels
  msg = sprintf("Deployment %s must include Kubernetes recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels", [kubernetes.name])
}
```

the output trace : 

```shell
ESC[34mTRACESC[0m - | | Enter data.main.recommended_labels
ESC[34mTRACESC[0m - | | | Eval data.main.recommended_labels
ESC[34mTRACESC[0m - | | | Index data.main.recommended_labels (matched 1 rule)
ESC[34mTRACESC[0m - | | | Enter data.main.recommended_labels
ESC[34mTRACESC[0m - | | | | Eval input.metadata.labels["app.kubernetes.io/name"]
ESC[34mTRACESC[0m - | | | | Fail input.metadata.labels["app.kubernetes.io/name"]
ESC[34mTRACESC[0m - | | | Fail data.main.recommended_labels
```

```
WARN - Deployment polaris-dashboard must include Kubernetes recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

6 tests, 5 passed, 1 warning, 0 failures
```

The manifest : 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    checksum/config: 8aa5a565fba7a2db98d46752087de8c1dcc83b70cd762c5829d5ba01270d54a2
  labels:
    app: polaris
    app.kubernetes.io/component: reporting
    app.kubernetes.io/instance: polaris-mycustomer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: polaris
    app.kubernetes.io/part-of: reporting-kubernetes
    app.kubernetes.io/version: v0.6.0
    component: dashboard
    env: staging
  name: polaris-dashboard
  namespace: reporting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polaris
      component: dashboard
```

If i change recommanded_labels with : 

```rego
recommended_labels {
  # input.metadata.labels["app.kubernetes.io/name"]
  # input.metadata.labels["app.kubernetes.io/instance"]
  # input.metadata.labels["app.kubernetes.io/version"]
  # input.metadata.labels["app.kubernetes.io/component"]
  # input.metadata.labels["app.kubernetes.io/part-of"]
  # input.metadata.labels["app.kubernetes.io/managed-by"]
  input.metadata.labels["app"]
}
```

It works : 

```
6 tests, 6 passed, 0 warnings, 0 failures
```
