### ISSUE TITLE
Redundant testing/ouput in versions >= 0.7.0

### ISSUE THREAD

**Issue by yurrriq** [instrumenta/conftest#38]
Version 0.6.0 worked great, but with 0.7.0 and 0.9.0, conftest seems to be rerunning my policies multiple times when I run `conftest test`. Is there some change I need to make? My policies don't differ structurally from the kubernetes example in the repo.

**Comment by garethr** [comment]
Sounds like a bug. Could you include an example and some output? Will look into.

**Comment by mKamleiter** [comment]
Hi, I'm working with 0.9.0 and get a similiar Output.
I'm testing a openshift route object using helm:
``` 
apiVersion: route.openshift.io/v1
 kind: Route
 metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  host: foobar
  tls:
    termination: Edge
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
  wildcardPolicy: None
```

My simple policy:
```
package main

deny[msg] {
  input.kind = "Route"
  name = input.metadata.name
  not input.spec.tls.termination
  msg = sprintf("%s/%s has to be secure", [kind,name])
}

deny[msg] {
  input.kind = "Route"
  name = input.metadata.name
  input.spec.host
  msg = sprintf("%s/%s can not contain the \"spec.host\" attribute", [input.kind,name])
}
```


Just the second policy should fail, the first is good, but the output is the following:


```
[user@rhel7 helm]$ helm template . | conftest test -
   Route/infra-test can not contain the "spec.host" attribute
   Route/infra-test can not contain the "spec.host" attribute
```

Once I delete the **not** failing policy it's working like it should:
```
[user@rhel7 helm]$ helm template . | conftest test -
   Route/infra-test can not contain the "spec.host" attribute
```
